Controllers/ApartmentsVisitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Npgsql;
using WebHome.Domain.Models;
using WebHome.Domain.Models.Home;
using WebHome.Domain.Services;

namespace WebHome.Controllers
{
    public class ApartmentsVisitorController : Controller
    {
        public static ApartmentsVisitor apartments_info_model;
        public static List<Rate> rates;
        public IActionResult Index()
        {
            return View("/Views/ApartmentsVisitor.cshtml");
        }

        [HttpPost]
        public ApartmentsVisitor CatchInfos([FromBody] string values)
        {
            apartments_info_model = JsonConvert.DeserializeObject<ApartmentsVisitor>(values);
            return apartments_info_model;
        }

        [HttpGet]
        public string GetApartments()
        {
            var data = new List<Rate>();
            try
            {
                var service_item = new RatesService();
                var rates_list = new RatesList(service_item);
                data = rates_list.rates;
                rates = data;
            }
            catch(Exception ex)
            {

            }
            var str = JsonConvert.SerializeObject(data);
            return str;
        }

        [HttpGet]
        public string GetFilteredApartments()
        {

            var data = new List<Rate>();
            var service_item = new RatesService();
            rates = service_item.rates();
            data = service_item.filter_list_visitor(rates,apartments_info_model);
            var str = JsonConvert.SerializeObject(data);
            return str;
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Npgsql;
using WebHome.Models;

namespace WebHome.Controllers
{
    public class LoginController : Controller
    {
        public static Session user_session_created = new Session(-1, -1, "Visitor", -1);
        public IActionResult Index()
        {
            return View("/Views/Login.cshtml");
        }

        [HttpPost]
        public IActionResult Authenticate([FromBody]Login values)
        {
            IActionResult response = Ok();
            try
            {
                var db = new DB();
                var data = new List<Login>();
                var Query = @"select usrname,pass,user_id,role_id from register where usrname = @m_usrname and pass = @m_pass and accepted = 1";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_usrname", values.usrname);
                cmd.Parameters.AddWithValue("@m_pass", values.pass);
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                NpgsqlDataReader DataReader;

                DataReader = cmd.ExecuteReader();

                cmd.Dispose();
                if (DataReader.HasRows)
                {
                    while (DataReader.Read())
                    {
                        data.Add(new Login
                        {
                            usrname = DataReader.GetValue(0).ToString(),
                            pass = DataReader.GetValue(1).ToString(),
                            user_id = Convert.ToInt32(DataReader.GetValue(2)),
                            role_id = Convert.ToInt32(DataReader.GetValue(3))
                        });
                    }


                }
                DataReader.Close();
                DataReader.Dispose();
                db.close();
                if (data.Count > 0)
                {
                    user_session_created = new Session(data[0].user_id, data[0].role_id, data[0].usrname, 1);
                    History();
                    response = Ok();
                }
                else
                {
                    user_session_created = new Session(-1, -1, "", -1);
                }

            }
            catch (Exception ex)
            {

            }
            return response;
        }

        [HttpGet]
        public JsonResult Log()
        {
            int res = 0;
            if (user_session_created.isloggedIn == 1 && user_session_created.role_id == 0) {
                res = 1;
            }
            else if(user_session_created.isloggedIn == 1 && user_session_created.role_id == 1)
            {
                res = 2; //host 
            }
            else if(user_session_created.isloggedIn == 1 && user_session_created.role_id == 2)
            {
                res = 3; //tenant
            }
            else if(user_session_created.isloggedIn == 1 && user_session_created.role_id == 3)
            {
                res = 4; //both
            }
            var obj = new
            {
                valid = res
            };
            return Json(obj); 
        }

        [HttpPost]
        public void History()
        {
            try
            {
                var db = new DB();
                var Query = @"INSERT INTO login (user_id, last_login) 
                                VALUES (@m_user_id,@m_last_login)";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_user_id", user_session_created.user_id);
                cmd.Parameters.AddWithValue("@m_last_login", DateTime.Now);
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();

            }
            catch(Exception ex)
            {

            }
        }

        [HttpGet]
        public string Logout()
        {
            var str = "bye";
            user_session_created = new Session(-1, -1, "", -1);
            return str;
        }
    }
}

Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using WebHome.Domain.Models;

namespace WebHome.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View("/Views/Register.cshtml");
        }

        [HttpPost]
        public IActionResult Register([FromBody] User values)
        {
            try
            {
                var db = new DB();
                int id = Create_Id(db.npgsqlConnection);
                var Query = @"INSERT INTO register (user_id, role_id, usrname, pass, name, surname,phone_number, images,created_on,email,accepted) 
                                VALUES (@m_user_id,@m_role_id,@m_usrname,@m_pass,@m_name,@m_surname,@m_phone_number,@m_images,@m_created_on,@m_email,@m_accepted)";
                var cmd = new  NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_images", values.images);
                cmd.Parameters.AddWithValue("@m_email", values.email);
                cmd.Parameters.AddWithValue("@m_phone_number", values.phone_number);
                cmd.Parameters.AddWithValue("@m_usrname", values.usrname);
                cmd.Parameters.AddWithValue("@m_pass", values.pass);
                cmd.Parameters.AddWithValue("@m_name", values.name);
                cmd.Parameters.AddWithValue("@m_surname", values.surname);
                cmd.Parameters.AddWithValue("m_created_on", DateTime.Now);
                cmd.Parameters.AddWithValue("@m_user_id", id);
                cmd.Parameters.AddWithValue("@m_role_id", values.role_id);
                if(values.role_id == 1 || values.role_id == 3)
                {
                    cmd.Parameters.AddWithValue("@m_accepted", 0);
                }
                else
                {
                    cmd.Parameters.AddWithValue("@m_accepted", 1);
                }
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();
            }
            catch (Exception ex)
            {

            }
            return Ok();
        }

        public int Create_Id(NpgsqlConnection npgsqlConnection)
        {
            int id = -1;
            try
            {
                
                var Cmd = new NpgsqlCommand();
                var Query = @"select max(user_id) from register";
                Cmd.CommandText = Query;
                Cmd.Connection = npgsqlConnection;
                NpgsqlDataReader DataReader;
            
                DataReader = Cmd.ExecuteReader();

                Cmd.Dispose();
                if (DataReader.HasRows)
                {
                        while (DataReader.Read())
                        {
                            var paramValue = DataReader.GetValue(0);
                            if (!(paramValue is DBNull))
                                id = Convert.ToInt32(DataReader.GetValue(0));
                            else
                                id = -1;
                        }

                }
                DataReader.Close();
                DataReader.Dispose();

            }
            catch(Exception ex)
            {

            }

            return id+1;
        }

        [HttpGet]
        public JsonResult UsrExist(string value)
        {
            bool result = false;
            int res = 0;
           
            try
            {
                var db = new DB();
                var Query = @"select exists(select 1 from register where usrname = @m_usrname)";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_usrname", value);
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                
                NpgsqlDataReader DataReader;

                DataReader = cmd.ExecuteReader();

                cmd.Dispose();
                if (DataReader.HasRows)
                {
                    while (DataReader.Read())
                    {
                        result = Convert.ToBoolean(DataReader.GetValue(0));
                    }

                }
                DataReader.Close();
                DataReader.Dispose();
                if(result == true)
                {
                    res = 1;
                }
                else
                {
                    res = 0;
                }
                db.close();
            }
            catch(Exception ex)
            {

            }
            var obj = new
            {
                valid = res
            };
            return Json(obj);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> WebHome</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebHome</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1" id="onhome">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApartmentsVisitor" asp-action="Index">Apartments</a>
                        </li>
                    </ul>
                </div>
                <div id="pageuser"></div>
                <div id="pageuser1"></div>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Register</a>
                    </li>
                </ul>
                <div id="userlogged">
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script type="text/javascript">
        var WebSiteUrl = "@Configs.WebSiteUrl";
        var log = @WebHome.Controllers.LoginController.user_session_created.isloggedIn;
        var usrname = "@WebHome.Controllers.LoginController.user_session_created.usrname";
        var userid = "@WebHome.Controllers.LoginController.user_session_created.user_id";
        var role_user = @WebHome.Controllers.LoginController.user_session_created.role_id;
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>