Controllers/AccountSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using WebHome.Domain.IServices;
using WebHome.Domain.Models;
using WebHome.Domain.Services;

namespace WebHome.Controllers
{
    public class AccountSettingsController : Controller
    {
        public static User current_user;
        public IActionResult Index()
        {
            return View("/Views/AccountSettings.cshtml");
        }

        [HttpGet]
        public User GetCurrUser(string value)
        {
            var usr = new UserService();
            var usr_model = new UserModel(usr, Convert.ToInt32(value));
            current_user = usr_model.user;
            return current_user;
        }

        [HttpPut]
        public JsonResult UpdateUsername([FromBody] string value)
        {
            int res = 1;
            try
            {
                var srvc = new UserService();
                if(srvc.UsernameExists(value) != 1)
                {
                    current_user.usrname = value;
                }
                else
                {
                    res = 0;
                }

            }
            catch(Exception ex)
            {

            }
            var obj = new
            {
                valid = res
            };
            return Json(res);
        }

        [HttpPut]
        public IActionResult UpdatePass([FromBody] string values)
        {
            
            current_user.pass = values;
            return Ok();
        }

        [HttpPut]
        public IActionResult UpdateMail([FromBody] string values)
        {
            current_user.email = values;
            return Ok();
        }
        [HttpPut]
        public IActionResult UpdateName([FromBody] string values)
            {
            current_user.name = values;
            return Ok();
        }
        [HttpPut]
        public IActionResult UpdateSurname([FromBody] string values)
        {
            current_user.surname = values;
            return Ok();
        }
        [HttpPut]
        public IActionResult UpdatePhone([FromBody] string values)
        {
            current_user.phone_number = values;
            return Ok();
        }

        [HttpPut]
        public IActionResult UpdatePhoto([FromBody] string values)
        {
            current_user.images = values;
            return Ok();
        }

        [HttpPut]
        public IActionResult UpdateRole([FromBody] string values)
        {
            current_user.role_id = Convert.ToInt32(values);
            return Ok();
        }

        [HttpPut]
        public IActionResult UpdateAccount()
        {
            try
            {
                var db = new DB();
                var Query = @"Update register set  role_id= @m_role_id , usrname = @m_usrname, pass=@m_pass , name=@m_name, surname=@m_surname,phone_number=@m_phone_number, 
                                images=@m_images,email=@m_email,accepted=@m_accepted where user_id = @m_user_id";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_images", current_user.images);
                cmd.Parameters.AddWithValue("@m_email", current_user.email);
                cmd.Parameters.AddWithValue("@m_phone_number", current_user.phone_number);
                cmd.Parameters.AddWithValue("@m_usrname", current_user.usrname);
                cmd.Parameters.AddWithValue("@m_pass", current_user.pass);
                cmd.Parameters.AddWithValue("@m_name", current_user.name);
                cmd.Parameters.AddWithValue("@m_surname", current_user.surname);
                cmd.Parameters.AddWithValue("@m_user_id", current_user.user_id);
                cmd.Parameters.AddWithValue("@m_role_id", current_user.role_id);
                cmd.Parameters.AddWithValue("@m_accepted", 1);
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();

            }
            catch(Exception ex)
            {

            }
            return Ok();
        }
       
    }
}

Controllers/ApartmentRentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebHome.Domain.Models;
using WebHome.Domain.Services;

namespace WebHome.Controllers
{
    public class ApartmentRentController : Controller
    {
        public static ApartmentsDetails apartment;

        public static User host = new User();

        public IActionResult Index()
        {
            return View("/Views/ApartmentRent.cshtml");
        }

        [HttpGet]
        public ApartmentsDetails GetApartment(string value)
        {
            var service = new ApartmentsListService();
            var all = new ApartmentsList(service);
            apartment = all.GetByID(Convert.ToInt32(value));
            return apartment;
        }

        [HttpGet]
        public User GetUserHost()
        {
            var service = new UserService();
            var user_host = new UserModel(service, apartment.user_id);
            host = user_host.user;
            return host;
        }

    }
}

Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Npgsql;
using WebHome.Domain.Models;

namespace WebHome.Controllers
{
    public class ApartmentsController : Controller
    {
        public IActionResult Index()
        {
            return View("/Views/Apartments.cshtml");
        }

        [HttpGet] 
        public string GetApartments(string value)
        {
            var data = new List<Apartments>();
            try
            {
                var db = new DB();
                var Query = @"select id, address, free_from, free_to  from apartments where user_id = @m_user_id";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_user_id", Int32.Parse(value));
                cmd.Connection = db.npgsqlConnection;
                NpgsqlDataReader DataReader;

                DataReader = cmd.ExecuteReader();

                cmd.Dispose();
                if (DataReader.HasRows)
                {

                    while (DataReader.Read())
                    {
                        data.Add(new Apartments
                        {
                            id = Convert.ToInt32(DataReader.GetValue(0)),
                            address = DataReader.GetValue(1).ToString(),
                            free_from = Convert.ToDateTime(DataReader.GetValue(2)),
                            free_to = Convert.ToDateTime(DataReader.GetValue(3)),
       
                        });
                    }


                }
                DataReader.Close();
                DataReader.Dispose();
                db.close();

            }
            catch(Exception ex)
            {

            }
            var str = JsonConvert.SerializeObject(data);
            return str;
        }

        [HttpPost]
        public IActionResult InsertApartment([FromBody] string value)
        {
            try
            {
                ApartmentsDetails values = JsonConvert.DeserializeObject<ApartmentsDetails>(value);
                var db = new DB();
                var Query = @"INSERT INTO apartments (user_id, address, reach_place, free_from, free_to, max_people,min_price, cost_per_person,description,num_beds,num_baths,num_bedrooms,area,rules,images,lonlat, type_description) 
                                VALUES (@m_user_id, @m_address, @m_reach_place, @m_free_from, @m_free_to, @m_max_people,@m_min_price, @m_cost_per_person,@m_description,@m_num_beds,@m_num_baths,@m_num_bedrooms,@m_area,@m_rules,@m_images,@m_lonlat,@m_type_description)";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_user_id", values.user_id);
                cmd.Parameters.AddWithValue("@m_address", values.apartment.address);
                cmd.Parameters.AddWithValue("@m_reach_place", values.reach_place);
                cmd.Parameters.AddWithValue("@m_free_from", values.apartment.free_from);
                cmd.Parameters.AddWithValue("@m_free_to", values.apartment.free_to);
                cmd.Parameters.AddWithValue("@m_max_people", values.max_people);
                cmd.Parameters.AddWithValue("@m_min_price", values.min_price);
                cmd.Parameters.AddWithValue("m_cost_per_person", values.cost_per_person);
                cmd.Parameters.AddWithValue("@m_description", values.description);
                cmd.Parameters.AddWithValue("@m_num_beds", values.num_beds);
                cmd.Parameters.AddWithValue("@m_num_baths", values.num_baths);
                cmd.Parameters.AddWithValue("@m_num_bedrooms", values.num_bedrooms);
                cmd.Parameters.AddWithValue("@m_area", values.area);
                cmd.Parameters.AddWithValue("@m_rules", values.rules);
                cmd.Parameters.AddWithValue("@m_images", values.images);
                cmd.Parameters.AddWithValue("@m_lonlat", values.lonlat);
                cmd.Parameters.AddWithValue("@m_type_description", values.type_description);
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();
            }
            catch(Exception Ex)
            {

            }
            return View("/Views/Apartments.cshtml");
        }
    }
}

Controllers/ApartmentsDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Npgsql;
using WebHome.Domain.IServices;
using WebHome.Domain.Models;
using WebHome.Domain.Services;

namespace WebHome.Controllers
{
    public class ApartmentsDetailsController : Controller
    {
        public static ApartmentsDetails apartment = new ApartmentsDetails();
        public IActionResult Index()
        {
            return View("/Views/ApartmentsDetails.cshtml");
        }

        [HttpGet]
        public ApartmentsDetails GetInfoApartments(string value)
        {
            var ap = new ApartmentsListService();
            var apartments = new ApartmentsList(ap);
            var current_apartment = new ApartmentsDetails();
            try
            {
                current_apartment = apartments.GetByID(Convert.ToInt32(value));
            }
            catch(Exception ex)
            {

            }
            apartment = current_apartment;
            return current_apartment;

        }

        [HttpPut]
        public IActionResult UpdatePlace([FromBody] string value)
        {
            try
            {
                ApartmentsDetails values = JsonConvert.DeserializeObject<ApartmentsDetails>(value);
                var db = new DB();
                var Query = @"UPDATE apartments SET address = @m_address, reach_place = @m_reach_place, free_from = @m_free_from, free_to = @m_free_to, " +
                    "max_people = @m_max_people, min_price= @m_min_price, cost_per_person= @m_cost_per_person, description= @m_description, " +
                    "num_beds= @m_num_beds, num_baths= @m_num_baths, num_bedrooms= @m_num_bedrooms, area= @m_area, " +
                    "rules= @m_rules, images= @m_images, lonlat= @m_lonlat, type_description= @m_type_description WHERE id = @m_id"; 
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_id", values.apartment.id);
                cmd.Parameters.AddWithValue("@m_address", values.apartment.address);
                cmd.Parameters.AddWithValue("@m_reach_place", values.reach_place);
                cmd.Parameters.AddWithValue("@m_free_from", values.apartment.free_from);
                cmd.Parameters.AddWithValue("@m_free_to", values.apartment.free_to);
                cmd.Parameters.AddWithValue("@m_max_people", values.max_people);
                cmd.Parameters.AddWithValue("@m_min_price", values.min_price);
                cmd.Parameters.AddWithValue("m_cost_per_person", values.cost_per_person);
                cmd.Parameters.AddWithValue("@m_description", values.description);
                cmd.Parameters.AddWithValue("@m_num_beds", values.num_beds);
                cmd.Parameters.AddWithValue("@m_num_baths", values.num_baths);
                cmd.Parameters.AddWithValue("@m_num_bedrooms", values.num_bedrooms);
                cmd.Parameters.AddWithValue("@m_area", values.area);
                cmd.Parameters.AddWithValue("@m_rules", values.rules);
                cmd.Parameters.AddWithValue("@m_images", values.images);
                cmd.Parameters.AddWithValue("@m_lonlat", values.lonlat);
                cmd.Parameters.AddWithValue("@m_type_description", values.type_description);
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();
            }
            catch(Exception ex)
            {

            }
            return Ok();
        }

        [HttpDelete]
        public IActionResult DeletePlace([FromBody] string value)
        {
            var ap = new ApartmentsListService();
            var apartments = new ApartmentsList(ap);
            try
            {
                apartments.DeleteApartment(Convert.ToInt32(value),ap);
                
            }
            catch(Exception ex)
            {

            }
            return Ok();
        }
    }
}

Controllers/BookingHostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using WebHome.Domain.Models;
using WebHome.Domain.Services;

namespace WebHome.Controllers
{
    public class BookingHostController : Controller
    {
        public IActionResult Index()
        {
            return View("/Views/BookingHost.cshtml");
        }

        [HttpGet]
        public List<BookHost> GetBookings(string value)
        {
            var service = new BookingsService();
            var listBookings = service.Get_bookings_current_host(Convert.ToInt32(value));
            return listBookings;
        }

        [HttpPut]
        public IActionResult AcceptBooking([FromBody] string value)
        {
            try
            {
                var db = new DB();
                var Query = @"UPDATE bookings SET closed = 1 where id = @m_id";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_id", Convert.ToInt32(value));
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();
            }
            catch(Exception ex)
            {

            }
            return Ok();
        }

        [HttpDelete]
        public IActionResult DeleteBooking([FromBody]string value)
        {
            try
            {
                var db = new DB();
                var Query = @"DELETE FROM bookings WHERE id = @m_id";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_id", Convert.ToInt32(value));
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();
            }
            catch(Exception ex)
            {

            }
            return Ok();
           
        }
    }
}

Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Npgsql;
using WebHome.Domain.Models;

namespace WebHome.Controllers
{
    public class MessagesController : Controller
    {
        public IActionResult Index()
        {
            return View("/Views/Messages.cshtml");
        }

        [HttpPost]
        public IActionResult Send([FromBody] string value)
        {
            try
            {
                Message values = JsonConvert.DeserializeObject<Message>(value);
                var db = new DB();
                var Query = @"INSERT INTO messages (from_user_id, to_user_id, message_body, apartment_id) 
                                VALUES (@m_user_id,@to_user_id,@m_message_body,@m_apartment)";
                var cmd = new NpgsqlCommand();
                cmd.CommandText = Query;
                cmd.Parameters.AddWithValue("@m_user_id", values.from_user_id);
                cmd.Parameters.AddWithValue("@to_user_id", values.to_user_id);
                cmd.Parameters.AddWithValue("@m_message_body", values.message_body);
                cmd.Parameters.AddWithValue("@m_apartment", values.apartment_id);
                cmd.Connection = db.npgsqlConnection;
                cmd.ExecuteNonQuery();
                db.close();
            }
            catch(Exception ex)
            {

            }
            return Ok();
        }
    }
}

Views/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
}

<h1>Admin</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/index.css" />
    <link rel="stylesheet" href="~/css/admin.css" />
</head>
<body>
    <br/>
    <table id="example" class="display" width="100%">
    </table>
    <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <div class="modal-header">
                <span class="close">&times;</span>
                <h2>Info of User</h2>
            </div>
            <div class="modal-body" id="mb">
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
    <br/><br/>
    <script type="text/javascript">
            var WebSiteUrl = "@Configs.WebSiteUrl";
    </script>
    <script src="~/js/admin.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/ApartmentRent.cshtml
@{
    ViewData["Title"] = "ApartmentRent";
}

<h1>Rent Apartment</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/apartmentrent.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.3.1/css/ol.css" type="text/css">
    <style>
        .map {
            height: 400px;
            width: 100%;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.3.1/build/ol.js"></script>
</head>
<body>
    <details>
        <summary><b>Place General Information</b></summary>
        <br />
        <label><b>Number of beds :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.num_beds beds</p>
        <br />
        <label><b>Number of bathrooms :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.num_baths bathrooms</p>
        <br />
        <label><b>Number of bedrooms :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.num_bedrooms bedrooms </p>
        <br />
        <label><b>Type of Apartment:</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.type_description type</p>
        <br />
        <label><b>Area :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.area  squared meters </p>
        <br />
    </details>
    <br />
    <details>
        <summary><b>Description</b></summary>
        <br />
        <label><b>Place is described from host as :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.description</p>
        <br />
    </details>
    <br />
    <details>
        <summary><b>Rules</b></summary>
        <br />
        <label><b>Rules for this place are :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.rules</p>
        <br />
    </details>
    <br />
    <details>
        <summary><b>Location</b></summary>
        <br />
        <label><b>Address :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.apartment.apartment.address </p>
        <br />
        <div id="smap" class="map"></div>
    </details>
    <br />
    <details>
        <summary><b>View Apartment</b></summary>
        <br />
        <img class="mySlides" src="@WebHome.Controllers.ApartmentRentController.apartment.images" style="width:50%">
        <br />
    </details>
    <br />
    <details>
        <summary><b>Host Info and Communication</b></summary>
        <br />
        <label><b>Host is :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.host.name @WebHome.Controllers.ApartmentRentController.host.surname </p>
        <br />
        <img class="mySlides" src="@WebHome.Controllers.ApartmentRentController.host.images" style="width:50%">
        <br />
        <label><b>Email :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.host.email</p>
        <br />
        <label><b>Phone number :</b></label>
        <p>@WebHome.Controllers.ApartmentRentController.host.phone_number</p>
        <ul class="navbar-nav flex-grow-1">
            <li class="liid">
                <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Index" style="position: center;"><u> Click to message Host </u></a>
            </li>
        </ul>
    </details>
    <br />
    
    <script type="text/javascript">
            var WebSiteUrl = "@Configs.WebSiteUrl";
    </script>
    <script src="~/js/apartmentrent.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Apartments.cshtml
@{
    ViewData["Title"] = "Apartments";
}

<h1>Apartments</h1>

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="~/css/apartments.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.3.1/css/ol.css" type="text/css">
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <style>
        .map {
            height: 400px;
            width: 100%;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.3.1/build/ol.js"></script>
</head>
<body>
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="BookingHost" asp-action="Index"><u>Booking requests</u></a>
        </li>
    </ul>
    <br/>
    <table id="example1" class="display" width="100%"></table>
    <br /><br />
    <button type="button" style="float: right;" class="addButton" onclick="AddPlace()">Add Place (+)</button>
    <br /><br />
    <div id="innerdiv"></div>
    <script type="text/javascript">
        var WebSiteUrl = "@Configs.WebSiteUrl";
        var usrid = @WebHome.Controllers.LoginController.user_session_created.user_id;
    </script>

    <script src="~/js/apartments.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Views/Booking.cshtml
@{
    ViewData["Title"] = "Booking";
}

<h1>Book Apartment</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/booking.css" />
</head>
<body>
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="ApartmentRent" asp-action="Index"><u> Return to Apartment's Details Page </u></a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Index"><u>Message host</u></a>
            </li>
        </ul>
    </div>
    <br /><br />
    <h2>Please confirm apartment's details: </h2><br />
    <p>@WebHome.Controllers.ApartmentRentController.apartment.apartment.address</p><br />
    <img class="mySlides" src="@WebHome.Controllers.ApartmentRentController.apartment.images" style="width:50%">
    <br /><br /><br />
    <label for="start1"><b>From:</b></label><input type="text" id="detailsstartdate_apartment" name="start1" value="@WebHome.Controllers.ApartmentRentController.apartment.apartment.free_from ">
    <label for="end1"><b>To:</b></label><input type="text" id="detailsenddate1_apartment" name="end1" value="@WebHome.Controllers.ApartmentRentController.apartment.apartment.free_to ">
    <label for="dstart1"><b>Change From:</b></label><input type="date" id="reservefrom" name="dstart1" onchange="checkAll()"><label for="dend1"><b>To:</b></label><input type="date" id="reserveto" name="dend1" onchange="checkAll()">
    <br /><br />
    <label for="bedr"> <b>Number of days you will occupy the apartment :</b></label> <input type="number" class="inpu" name="bedr" id="numdays"><br /><br />
    <label for="c"> <b>Cost per day :</b></label> <input type="text" class="inpu" name="c" id="costday" value="@WebHome.Controllers.ApartmentRentController.apartment.min_price"><br /><br />
    <label for="calc"> <b>Total cost :</b></label> <input type="text" class="inpu" name="cals" id="calc_cost"><br /><br />
    <label for="ca"> <b>Cost per person for one day :</b></label> <input type="text" class="inpu" name="ca" id="costdayperson" value="@WebHome.Controllers.ApartmentRentController.apartment.cost_per_person"><br /><br />
    <label for="caa"> <b>Total cost per person :</b></label> <input type="text" class="inpu" name="caa" id="costdaypersontotal"><br /><br />
    <button type="button" class="confirmButton" onclick="ConfirmPlace()">Confirm and Book</button>
    <script type="text/javascript">
        var WebSiteUrl = "@Configs.WebSiteUrl";
        var currUserlogged = "@WebHome.Controllers.LoginController.user_session_created.user_id";
        var currhost = "@WebHome.Controllers.ApartmentRentController.host.user_id";
        var currapartment = "@WebHome.Controllers.ApartmentRentController.apartment.apartment.id";
        var currfrom = "@WebHome.Controllers.ApartmentRentController.apartment.apartment.free_from";
        var currto = "@WebHome.Controllers.ApartmentRentController.apartment.apartment.free_to";
    </script>
    <script src="~/js/booking.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Messages.cshtml
@{
    ViewData["Title"] = "Messages";
}

<h1>Messages</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/message.css" />
</head>
<body>
    <ul class="navbar-nav flex-grow-1">
        <li class="liid">
            <a class="nav-link text-dark" asp-area="" asp-controller="ApartmentRent" asp-action="Index" style="position: center;"><u> Return to Apartment's Details Page </u></a>
        </li>
    </ul>
    <br /><br />
    <label for="fromuser"><b>From :</b></label>
    <br />
    <input type="text" class="inpu" name="fromuser" id="from_user" value="@WebHome.Controllers.LoginController.user_session_created.usrname">
    <br />
    <br />

    <label for="to"><b>To : </b></label>
    <br />
    <input type="text" class="inpu" name="to" id="to_user" value="@WebHome.Controllers.ApartmentRentController.host.usrname">
    <br />
    <br />
    <label for="mess"><b>Message Body :</b></label>
    <br />
    <textarea class="inpu" id="message" rows="3" cols="80" name="mess"></textarea><br /><br />
    <br />
    <br />
    <button class="sendButton" onclick="Send()">Send</button>
    <br />
    <button class="bookButton" onclick="Book()">Book Now</button>
    <script type="text/javascript">
        var WebSiteUrl = "@Configs.WebSiteUrl";
        var currUserlogged = "@WebHome.Controllers.LoginController.user_session_created.user_id";
        var currhost = "@WebHome.Controllers.ApartmentRentController.host.user_id";
        var currapartment = "@WebHome.Controllers.ApartmentRentController.apartment.apartment.id";
        var currfrom = "@WebHome.Controllers.ApartmentRentController.apartment.apartment.free_from";
        var currto = "@WebHome.Controllers.ApartmentRentController.apartment.apartment.free_to";
        var curr_role = @WebHome.Controllers.LoginController.user_session_created.role_id;
    </script>
    <script src="~/js/messages.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>